import { Project, GitCommit, ScopeAlert, ActivityEvent } from './types';

const stylecartCommits: GitCommit[] = [
  {
    id: 'commit-001',
    message: 'feat: implement user authentication with JWT',
    developer: 'alex-sharma',
    timestamp: Date.now() - 172800000,
    filesChanged: 12,
    linesAdded: 456,
    linesRemoved: 89,
    relatedRequirementId: 'core-1',
    aiClassification: 'core_feature',
    confidence: 0.95,
  },
  {
    id: 'commit-002',
    message: 'feat: product catalogue with pagination',
    developer: 'alex-sharma',
    timestamp: Date.now() - 158400000,
    filesChanged: 18,
    linesAdded: 678,
    linesRemoved: 145,
    relatedRequirementId: 'core-2',
    aiClassification: 'core_feature',
    confidence: 0.92,
  },
  {
    id: 'commit-003',
    message: 'fix: auth token refresh logic',
    developer: 'alex-sharma',
    timestamp: Date.now() - 144000000,
    filesChanged: 4,
    linesAdded: 78,
    linesRemoved: 42,
    relatedRequirementId: 'core-1',
    aiClassification: 'bug_fix',
    confidence: 0.88,
  },
  {
    id: 'commit-004',
    message: 'feat: advanced product search with filters',
    developer: 'alex-sharma',
    timestamp: Date.now() - 129600000,
    filesChanged: 24,
    linesAdded: 892,
    linesRemoved: 234,
    relatedRequirementId: 'core-3',
    aiClassification: 'core_feature',
    confidence: 0.90,
  },
  {
    id: 'commit-005',
    message: 'refactor: consolidate API utilities',
    developer: 'alex-sharma',
    timestamp: Date.now() - 115200000,
    filesChanged: 16,
    linesAdded: 234,
    linesRemoved: 567,
    aiClassification: 'refactor',
    confidence: 0.85,
  },
  {
    id: 'commit-006',
    message: 'feat: product detail page with reviews section',
    developer: 'alex-sharma',
    timestamp: Date.now() - 100800000,
    filesChanged: 22,
    linesAdded: 745,
    linesRemoved: 123,
    relatedRequirementId: 'core-4',
    aiClassification: 'core_feature',
    confidence: 0.91,
  },
  {
    id: 'commit-007',
    message: 'feat: shopping cart with persistent storage',
    developer: 'alex-sharma',
    timestamp: Date.now() - 86400000,
    filesChanged: 19,
    linesAdded: 612,
    linesRemoved: 89,
    relatedRequirementId: 'core-5',
    aiClassification: 'core_feature',
    confidence: 0.93,
  },
  {
    id: 'commit-008',
    message: 'fix: cart calculation edge cases',
    developer: 'alex-sharma',
    timestamp: Date.now() - 72000000,
    filesChanged: 6,
    linesAdded: 145,
    linesRemoved: 34,
    relatedRequirementId: 'core-5',
    aiClassification: 'bug_fix',
    confidence: 0.87,
  },
  {
    id: 'commit-009',
    message: 'feat: checkout flow implementation',
    developer: 'alex-sharma',
    timestamp: Date.now() - 57600000,
    filesChanged: 28,
    linesAdded: 923,
    linesRemoved: 156,
    relatedRequirementId: 'core-6',
    aiClassification: 'core_feature',
    confidence: 0.89,
  },
  {
    id: 'commit-010',
    message: 'feat: Stripe payment integration',
    developer: 'alex-sharma',
    timestamp: Date.now() - 43200000,
    filesChanged: 17,
    linesAdded: 534,
    linesRemoved: 78,
    relatedRequirementId: 'core-7',
    aiClassification: 'core_feature',
    confidence: 0.94,
  },
  {
    id: 'commit-011',
    message: 'feat: implement dark mode styling',
    developer: 'alex-sharma',
    timestamp: Date.now() - 28800000,
    filesChanged: 34,
    linesAdded: 1200,
    linesRemoved: 450,
    aiClassification: 'scope_addition',
    confidence: 0.72,
  },
  {
    id: 'commit-012',
    message: 'feat: analytics dashboard tracking',
    developer: 'alex-sharma',
    timestamp: Date.now() - 14400000,
    filesChanged: 31,
    linesAdded: 1100,
    linesRemoved: 289,
    aiClassification: 'scope_addition',
    confidence: 0.68,
  },
  {
    id: 'commit-013',
    message: 'feat: order tracking system',
    developer: 'alex-sharma',
    timestamp: Date.now() - 7200000,
    filesChanged: 25,
    linesAdded: 876,
    linesRemoved: 145,
    relatedRequirementId: 'core-8',
    aiClassification: 'core_feature',
    confidence: 0.91,
  },
  {
    id: 'commit-014',
    message: 'test: add integration tests for payment flow',
    developer: 'alex-sharma',
    timestamp: Date.now() - 3600000,
    filesChanged: 12,
    linesAdded: 456,
    linesRemoved: 0,
    aiClassification: 'refactor',
    confidence: 0.82,
  },
  {
    id: 'commit-015',
    message: 'fix: payment failure edge case handling',
    developer: 'alex-sharma',
    timestamp: Date.now() - 1800000,
    filesChanged: 8,
    linesAdded: 234,
    linesRemoved: 78,
    aiClassification: 'bug_fix',
    confidence: 0.90,
  },
];

const stylecartScopeAlerts: ScopeAlert[] = [
  {
    id: 'alert-001',
    type: 'scope_addition',
    severity: 'medium',
    feature: 'Dark Mode',
    relatedCommitId: 'commit-011',
    description: 'Dark mode implementation detected in commits but not in original requirements.',
    recommendation: 'Review if dark mode should be added to scope or documented as an enhancement.',
    createdAt: Date.now() - 28800000,
    status: 'open',
  },
  {
    id: 'alert-002',
    type: 'scope_addition',
    severity: 'high',
    feature: 'Analytics Dashboard',
    relatedCommitId: 'commit-012',
    description: 'Analytics tracking system implemented. This was not in the core requirements.',
    recommendation: 'Clarify with client if analytics is a requirement or a bonus feature.',
    createdAt: Date.now() - 14400000,
    status: 'open',
  },
  {
    id: 'alert-003',
    type: 'requirement_mismatch',
    severity: 'medium',
    feature: 'Product Reviews',
    description: 'Product reviews section added in detail page but not explicitly required.',
    recommendation: 'Confirm this aligns with client expectations.',
    createdAt: Date.now() - 100800000,
    status: 'approved',
  },
];

const stylecartActivities: ActivityEvent[] = [
  {
    id: 'activity-001',
    type: 'commit',
    label: 'User authentication implemented',
    timestamp: Date.now() - 172800000,
    details: { commitId: 'commit-001', author: 'alex-sharma' },
  },
  {
    id: 'activity-002',
    type: 'requirement_update',
    label: 'Product catalogue requirement marked in progress',
    timestamp: Date.now() - 158400000,
    details: { requirementId: 'core-2' },
  },
  {
    id: 'activity-003',
    type: 'commit',
    label: 'Advanced search filters added',
    timestamp: Date.now() - 129600000,
    details: { commitId: 'commit-004', author: 'alex-sharma' },
  },
  {
    id: 'activity-004',
    type: 'requirement_update',
    label: 'Product details requirement marked in progress',
    timestamp: Date.now() - 100800000,
    details: { requirementId: 'core-4' },
  },
  {
    id: 'activity-005',
    type: 'scope_alert',
    label: 'Dark mode feature detected - scope addition flagged',
    timestamp: Date.now() - 28800000,
    details: { description: 'Not in original requirements' },
  },
  {
    id: 'activity-006',
    type: 'scope_alert',
    label: 'Analytics system detected - potential scope creep',
    timestamp: Date.now() - 14400000,
    details: { description: 'New feature detected in commits' },
  },
  {
    id: 'activity-007',
    type: 'requirement_update',
    label: 'Order tracking requirement marked in progress',
    timestamp: Date.now() - 7200000,
    details: { requirementId: 'core-8' },
  },
  {
    id: 'activity-008',
    type: 'commit',
    label: 'Payment handling improvements',
    timestamp: Date.now() - 3600000,
    details: { commitId: 'commit-014', author: 'alex-sharma' },
  },
  {
    id: 'activity-009',
    type: 'commit',
    label: 'Critical payment bug fixed',
    timestamp: Date.now() - 1800000,
    details: { commitId: 'commit-015', author: 'alex-sharma' },
  },
];

export const STYLECART: Project = {
  id: 'stylecart-dev',
  name: 'StyleCart',
  description: 'E-commerce platform for clothing business',
  status: 'in_development',
  progress: 68,
  targetUsers: 'Young adults looking for affordable fashion',
  platform: 'web',
  deadline: '2-3_months',
  coreRequirements: [
    {
      id: 'core-1',
      name: 'User registration & login',
      description: 'Allow users to create accounts and sign in securely',
      status: 'completed',
      priority: 'high',
      estimatedEffort: 'medium',
      completedAt: Date.now() - 158400000,
    },
    {
      id: 'core-2',
      name: 'Product catalogue',
      description: 'Display all available products with pagination',
      status: 'completed',
      priority: 'high',
      estimatedEffort: 'medium',
      completedAt: Date.now() - 129600000,
    },
    {
      id: 'core-3',
      name: 'Product search',
      description: 'Search and filter products by name, category, price',
      status: 'completed',
      priority: 'high',
      estimatedEffort: 'medium',
      completedAt: Date.now() - 100800000,
    },
    {
      id: 'core-4',
      name: 'Product details',
      description: 'View detailed product information, images, and reviews',
      status: 'completed',
      priority: 'high',
      estimatedEffort: 'small',
      completedAt: Date.now() - 86400000,
    },
    {
      id: 'core-5',
      name: 'Shopping cart',
      description: 'Add and manage products in cart',
      status: 'completed',
      priority: 'high',
      estimatedEffort: 'medium',
      completedAt: Date.now() - 72000000,
    },
    {
      id: 'core-6',
      name: 'Checkout process',
      description: 'Complete purchase process with address and payment info',
      status: 'completed',
      priority: 'high',
      estimatedEffort: 'medium',
      completedAt: Date.now() - 57600000,
    },
    {
      id: 'core-7',
      name: 'Online payment',
      description: 'Process payments securely through Stripe',
      status: 'completed',
      priority: 'high',
      estimatedEffort: 'large',
      completedAt: Date.now() - 43200000,
    },
    {
      id: 'core-8',
      name: 'Order tracking',
      description: 'Users can track their orders from placed to delivered',
      status: 'in_progress',
      priority: 'high',
      estimatedEffort: 'small',
    },
  ],
  addedRequirements: [
    {
      id: 'added-1',
      name: 'Payment Failure Handling',
      description: 'Graceful handling when payment fails',
      status: 'completed',
      priority: 'high',
      estimatedEffort: 'small',
      completedAt: Date.now() - 3600000,
    },
    {
      id: 'added-2',
      name: 'Refund & Cancellation Flow',
      description: 'Allow users to cancel orders and request refunds',
      status: 'pending',
      priority: 'high',
      estimatedEffort: 'medium',
    },
    {
      id: 'added-3',
      name: 'Mobile Responsiveness',
      description: 'Ensure works across all screen sizes',
      status: 'in_progress',
      priority: 'medium',
      estimatedEffort: 'medium',
    },
    {
      id: 'added-4',
      name: 'Security & Data Protection',
      description: 'Protect user data and payment information',
      status: 'in_progress',
      priority: 'high',
      estimatedEffort: 'large',
    },
  ],
  optionalAddOns: [
    { id: 'addon-1', name: 'Wishlist', description: 'Save products for later', status: 'available' },
    { id: 'addon-2', name: 'Product Reviews', description: 'Rate and review products', status: 'added' },
    { id: 'addon-3', name: 'AI Recommendations', description: 'Personalized suggestions', status: 'available' },
    { id: 'addon-4', name: 'Loyalty Program', description: 'Reward returning customers', status: 'available' },
  ],
  suggestions: [],
  projectHealth: {
    clarity: 88,
    note: 'Project well-defined. Main focus: completing order tracking and refund flow.',
  },
  timeline: [
    { id: '1', label: 'Project kickoff', completed: true, timestamp: Date.now() - 172800000 },
    { id: '2', label: 'Core auth & catalogue', completed: true, timestamp: Date.now() - 129600000 },
    { id: '3', label: 'Shopping cart & checkout', completed: true, timestamp: Date.now() - 57600000 },
    { id: '4', label: 'Order tracking & completion', completed: false },
  ],
  summary: 'Building a modern e-commerce platform with secure payments and order tracking.',
  createdAt: Date.now() - 259200000,
  gitRepository: 'github.com/stylecart/app',
  commits: stylecartCommits,
  scopeAlerts: stylecartScopeAlerts,
  activities: stylecartActivities,
  developmentHealth: {
    score: 72,
    reasons: [
      'Good commit frequency and testing',
      'Scope additions detected - requires review',
      'Payment handling improvements recent',
      'Missing refund cancellation flow',
    ],
    lastUpdated: Date.now(),
  },
};

const campusConnectCommits: GitCommit[] = [
  {
    id: 'commit-cc-001',
    message: 'initial: project setup with Next.js and database',
    developer: 'priya-patel',
    timestamp: Date.now() - 259200000,
    filesChanged: 45,
    linesAdded: 2300,
    linesRemoved: 0,
    aiClassification: 'core_feature',
    confidence: 0.85,
  },
  {
    id: 'commit-cc-002',
    message: 'feat: user authentication and profile management',
    developer: 'priya-patel',
    timestamp: Date.now() - 230400000,
    filesChanged: 28,
    linesAdded: 1200,
    linesRemoved: 150,
    relatedRequirementId: 'cc-req-1',
    aiClassification: 'core_feature',
    confidence: 0.91,
  },
  {
    id: 'commit-cc-003',
    message: 'feat: create and manage study groups',
    developer: 'priya-patel',
    timestamp: Date.now() - 201600000,
    filesChanged: 32,
    linesAdded: 1450,
    linesRemoved: 200,
    relatedRequirementId: 'cc-req-2',
    aiClassification: 'core_feature',
    confidence: 0.88,
  },
  {
    id: 'commit-cc-004',
    message: 'feat: messaging system between students',
    developer: 'priya-patel',
    timestamp: Date.now() - 172800000,
    filesChanged: 38,
    linesAdded: 1600,
    linesRemoved: 300,
    relatedRequirementId: 'cc-req-3',
    aiClassification: 'core_feature',
    confidence: 0.89,
  },
  {
    id: 'commit-cc-005',
    message: 'fix: messaging performance issues',
    developer: 'priya-patel',
    timestamp: Date.now() - 158400000,
    filesChanged: 8,
    linesAdded: 145,
    linesRemoved: 234,
    aiClassification: 'bug_fix',
    confidence: 0.86,
  },
  {
    id: 'commit-cc-006',
    message: 'feat: course and assignment tracking',
    developer: 'priya-patel',
    timestamp: Date.now() - 129600000,
    filesChanged: 26,
    linesAdded: 980,
    linesRemoved: 120,
    relatedRequirementId: 'cc-req-4',
    aiClassification: 'core_feature',
    confidence: 0.87,
  },
  {
    id: 'commit-cc-007',
    message: 'feat: document sharing in groups',
    developer: 'priya-patel',
    timestamp: Date.now() - 100800000,
    filesChanged: 22,
    linesAdded: 756,
    linesRemoved: 89,
    relatedRequirementId: 'cc-req-5',
    aiClassification: 'core_feature',
    confidence: 0.85,
  },
];

const campusConnectScopeAlerts: ScopeAlert[] = [
  {
    id: 'alert-cc-001',
    type: 'feature_addition',
    severity: 'low',
    feature: 'Profile Customization',
    description: 'Extended profile options being developed beyond basic profile info.',
    recommendation: 'Ensure profile features align with scope.',
    createdAt: Date.now() - 230400000,
    status: 'approved',
  },
];

const campusConnectActivities: ActivityEvent[] = [
  {
    id: 'activity-cc-001',
    type: 'commit',
    label: 'Project foundation completed',
    timestamp: Date.now() - 259200000,
    details: { commitId: 'commit-cc-001' },
  },
  {
    id: 'activity-cc-002',
    type: 'requirement_update',
    label: 'User authentication completed',
    timestamp: Date.now() - 230400000,
    details: { requirementId: 'cc-req-1' },
  },
  {
    id: 'activity-cc-003',
    type: 'requirement_update',
    label: 'Study group management in progress',
    timestamp: Date.now() - 201600000,
    details: { requirementId: 'cc-req-2' },
  },
];

export const CAMPUSCONNECT: Project = {
  id: 'campusconnect-dev',
  name: 'CampusConnect',
  description: 'Student collaboration and study platform',
  status: 'in_development',
  progress: 45,
  targetUsers: 'College and university students',
  platform: 'web_mobile',
  deadline: '3+_months',
  coreRequirements: [
    {
      id: 'cc-req-1',
      name: 'User authentication',
      description: 'Secure student account management',
      status: 'completed',
      priority: 'high',
      estimatedEffort: 'medium',
      completedAt: Date.now() - 230400000,
    },
    {
      id: 'cc-req-2',
      name: 'Study group creation',
      description: 'Create and manage study groups',
      status: 'in_progress',
      priority: 'high',
      estimatedEffort: 'medium',
    },
    {
      id: 'cc-req-3',
      name: 'Messaging system',
      description: 'Real-time messaging between students',
      status: 'in_progress',
      priority: 'high',
      estimatedEffort: 'large',
    },
    {
      id: 'cc-req-4',
      name: 'Course tracking',
      description: 'Track courses and assignments',
      status: 'in_progress',
      priority: 'medium',
      estimatedEffort: 'medium',
    },
    {
      id: 'cc-req-5',
      name: 'Document sharing',
      description: 'Share notes and documents in groups',
      status: 'in_progress',
      priority: 'medium',
      estimatedEffort: 'medium',
    },
    {
      id: 'cc-req-6',
      name: 'User profiles',
      description: 'Student profiles with skills and interests',
      status: 'pending',
      priority: 'low',
      estimatedEffort: 'small',
    },
  ],
  addedRequirements: [
    {
      id: 'cc-added-1',
      name: 'Notifications System',
      description: 'Real-time notifications for messages and updates',
      status: 'pending',
      priority: 'high',
      estimatedEffort: 'medium',
    },
  ],
  optionalAddOns: [
    { id: 'cc-addon-1', name: 'Study Timer', description: 'Pomodoro timer for study sessions', status: 'available' },
    { id: 'cc-addon-2', name: 'Quiz Generator', description: 'Auto-generate quizzes from notes', status: 'available' },
    { id: 'cc-addon-3', name: 'Video Calling', description: 'Built-in video conferencing', status: 'available' },
  ],
  suggestions: [],
  projectHealth: {
    clarity: 82,
    note: 'Project requirements are clear but complex. Focus on core messaging and group features first.',
  },
  timeline: [
    { id: '1', label: 'Project setup', completed: true, timestamp: Date.now() - 259200000 },
    { id: '2', label: 'Auth and core features', completed: true, timestamp: Date.now() - 129600000 },
    { id: '3', label: 'Advanced features and polish', completed: false },
    { id: '4', label: 'Testing and deployment', completed: false },
  ],
  summary: 'Building a collaborative platform for student groups and study management.',
  createdAt: Date.now() - 345600000,
  gitRepository: 'github.com/campusconnect/platform',
  commits: campusConnectCommits,
  scopeAlerts: campusConnectScopeAlerts,
  activities: campusConnectActivities,
  developmentHealth: {
    score: 58,
    reasons: [
      'Steady progress on core features',
      'Messaging system needs performance optimization',
      'Missing notification system implementation',
      'Mobile responsiveness needs work',
    ],
    lastUpdated: Date.now(),
  },
};

const fitflowCommits: GitCommit[] = [
  {
    id: 'commit-ff-001',
    message: 'feat: complete fitness tracking dashboard',
    developer: 'raj-kumar',
    timestamp: Date.now() - 518400000,
    filesChanged: 52,
    linesAdded: 3200,
    linesRemoved: 400,
    relatedRequirementId: 'ff-req-1',
    aiClassification: 'core_feature',
    confidence: 0.94,
  },
  {
    id: 'commit-ff-002',
    message: 'feat: workout logging and history',
    developer: 'raj-kumar',
    timestamp: Date.now() - 489600000,
    filesChanged: 38,
    linesAdded: 2100,
    linesRemoved: 300,
    relatedRequirementId: 'ff-req-2',
    aiClassification: 'core_feature',
    confidence: 0.93,
  },
  {
    id: 'commit-ff-003',
    message: 'feat: nutrition tracking and meal plans',
    developer: 'raj-kumar',
    timestamp: Date.now() - 460800000,
    filesChanged: 44,
    linesAdded: 2450,
    linesRemoved: 350,
    relatedRequirementId: 'ff-req-3',
    aiClassification: 'core_feature',
    confidence: 0.91,
  },
  {
    id: 'commit-ff-004',
    message: 'feat: AI-powered personalized workout recommendations',
    developer: 'raj-kumar',
    timestamp: Date.now() - 432000000,
    filesChanged: 48,
    linesAdded: 2800,
    linesRemoved: 500,
    relatedRequirementId: 'ff-req-4',
    aiClassification: 'core_feature',
    confidence: 0.89,
  },
  {
    id: 'commit-ff-005',
    message: 'feat: social features and friend tracking',
    developer: 'raj-kumar',
    timestamp: Date.now() - 403200000,
    filesChanged: 36,
    linesAdded: 1950,
    linesRemoved: 280,
    relatedRequirementId: 'ff-req-5',
    aiClassification: 'core_feature',
    confidence: 0.90,
  },
  {
    id: 'commit-ff-006',
    message: 'feat: wearable device integration',
    developer: 'raj-kumar',
    timestamp: Date.now() - 374400000,
    filesChanged: 32,
    linesAdded: 1700,
    linesRemoved: 200,
    relatedRequirementId: 'ff-req-6',
    aiClassification: 'core_feature',
    confidence: 0.88,
  },
  {
    id: 'commit-ff-007',
    message: 'fix: wearable sync reliability',
    developer: 'raj-kumar',
    timestamp: Date.now() - 345600000,
    filesChanged: 12,
    linesAdded: 456,
    linesRemoved: 234,
    aiClassification: 'bug_fix',
    confidence: 0.92,
  },
  {
    id: 'commit-ff-008',
    message: 'feat: premium subscription tiers',
    developer: 'raj-kumar',
    timestamp: Date.now() - 316800000,
    filesChanged: 28,
    linesAdded: 1200,
    linesRemoved: 150,
    relatedRequirementId: 'ff-req-7',
    aiClassification: 'core_feature',
    confidence: 0.87,
  },
  {
    id: 'commit-ff-009',
    message: 'feat: progress reports and analytics',
    developer: 'raj-kumar',
    timestamp: Date.now() - 288000000,
    filesChanged: 40,
    linesAdded: 1890,
    linesRemoved: 320,
    relatedRequirementId: 'ff-req-8',
    aiClassification: 'core_feature',
    confidence: 0.86,
  },
  {
    id: 'commit-ff-010',
    message: 'refactor: optimize database queries',
    developer: 'raj-kumar',
    timestamp: Date.now() - 259200000,
    filesChanged: 24,
    linesAdded: 890,
    linesRemoved: 1200,
    aiClassification: 'refactor',
    confidence: 0.88,
  },
  {
    id: 'commit-ff-011',
    message: 'test: comprehensive integration tests',
    developer: 'raj-kumar',
    timestamp: Date.now() - 230400000,
    filesChanged: 18,
    linesAdded: 2340,
    linesRemoved: 0,
    aiClassification: 'refactor',
    confidence: 0.85,
  },
  {
    id: 'commit-ff-012',
    message: 'feat: mobile app push notifications',
    developer: 'raj-kumar',
    timestamp: Date.now() - 201600000,
    filesChanged: 22,
    linesAdded: 1100,
    linesRemoved: 180,
    relatedRequirementId: 'ff-req-9',
    aiClassification: 'core_feature',
    confidence: 0.89,
  },
  {
    id: 'commit-ff-013',
    message: 'feat: offline mode support',
    developer: 'raj-kumar',
    timestamp: Date.now() - 172800000,
    filesChanged: 26,
    linesAdded: 1450,
    linesRemoved: 290,
    aiClassification: 'scope_addition',
    confidence: 0.75,
  },
  {
    id: 'commit-ff-014',
    message: 'fix: various stability improvements',
    developer: 'raj-kumar',
    timestamp: Date.now() - 144000000,
    filesChanged: 15,
    linesAdded: 580,
    linesRemoved: 340,
    aiClassification: 'bug_fix',
    confidence: 0.91,
  },
  {
    id: 'commit-ff-015',
    message: 'feat: leaderboards and achievements',
    developer: 'raj-kumar',
    timestamp: Date.now() - 115200000,
    filesChanged: 34,
    linesAdded: 1650,
    linesRemoved: 220,
    aiClassification: 'scope_addition',
    confidence: 0.70,
  },
];

const fitflowScopeAlerts: ScopeAlert[] = [
  {
    id: 'alert-ff-001',
    type: 'scope_addition',
    severity: 'low',
    feature: 'Offline Mode',
    relatedCommitId: 'commit-ff-013',
    description: 'Offline functionality implemented beyond original scope.',
    recommendation: 'Verify if this feature should be included in initial launch.',
    createdAt: Date.now() - 172800000,
    status: 'approved',
  },
  {
    id: 'alert-ff-002',
    type: 'feature_addition',
    severity: 'low',
    feature: 'Leaderboards & Achievements',
    relatedCommitId: 'commit-ff-015',
    description: 'Gamification elements added to increase user engagement.',
    recommendation: 'Nice addition - aligns with fitness app best practices.',
    createdAt: Date.now() - 115200000,
    status: 'approved',
  },
];

const fitflowActivities: ActivityEvent[] = [
  {
    id: 'activity-ff-001',
    type: 'requirement_update',
    label: 'Fitness tracking dashboard completed',
    timestamp: Date.now() - 518400000,
    details: { requirementId: 'ff-req-1' },
  },
  {
    id: 'activity-ff-002',
    type: 'requirement_update',
    label: 'Nutrition tracking completed',
    timestamp: Date.now() - 460800000,
    details: { requirementId: 'ff-req-3' },
  },
  {
    id: 'activity-ff-003',
    type: 'requirement_update',
    label: 'Wearable integration completed',
    timestamp: Date.now() - 374400000,
    details: { requirementId: 'ff-req-6' },
  },
  {
    id: 'activity-ff-004',
    type: 'requirement_update',
    label: 'Premium tiers launched',
    timestamp: Date.now() - 316800000,
    details: { requirementId: 'ff-req-7' },
  },
];

export const FITFLOW: Project = {
  id: 'fitflow-dev',
  name: 'FitFlow',
  description: 'AI-powered fitness tracking and wellness platform',
  status: 'in_development',
  progress: 88,
  targetUsers: 'Fitness enthusiasts and health-conscious individuals',
  platform: 'web_mobile',
  deadline: '1-2_weeks',
  coreRequirements: [
    {
      id: 'ff-req-1',
      name: 'Fitness tracking dashboard',
      description: 'Real-time workout metrics and progress',
      status: 'completed',
      priority: 'high',
      estimatedEffort: 'large',
      completedAt: Date.now() - 518400000,
    },
    {
      id: 'ff-req-2',
      name: 'Workout logging',
      description: 'Log and track workout history',
      status: 'completed',
      priority: 'high',
      estimatedEffort: 'medium',
      completedAt: Date.now() - 489600000,
    },
    {
      id: 'ff-req-3',
      name: 'Nutrition tracking',
      description: 'Track meals and nutrition information',
      status: 'completed',
      priority: 'high',
      estimatedEffort: 'large',
      completedAt: Date.now() - 460800000,
    },
    {
      id: 'ff-req-4',
      name: 'AI recommendations',
      description: 'Personalized workout and nutrition suggestions',
      status: 'completed',
      priority: 'high',
      estimatedEffort: 'large',
      completedAt: Date.now() - 432000000,
    },
    {
      id: 'ff-req-5',
      name: 'Social features',
      description: 'Connect with friends and track together',
      status: 'completed',
      priority: 'medium',
      estimatedEffort: 'medium',
      completedAt: Date.now() - 403200000,
    },
    {
      id: 'ff-req-6',
      name: 'Wearable integration',
      description: 'Sync with fitness wearables',
      status: 'completed',
      priority: 'high',
      estimatedEffort: 'medium',
      completedAt: Date.now() - 374400000,
    },
    {
      id: 'ff-req-7',
      name: 'Premium subscriptions',
      description: 'Tiered subscription with premium features',
      status: 'completed',
      priority: 'high',
      estimatedEffort: 'medium',
      completedAt: Date.now() - 316800000,
    },
    {
      id: 'ff-req-8',
      name: 'Progress reports',
      description: 'Detailed analytics and progress tracking',
      status: 'completed',
      priority: 'medium',
      estimatedEffort: 'large',
      completedAt: Date.now() - 288000000,
    },
    {
      id: 'ff-req-9',
      name: 'Push notifications',
      description: 'Mobile app notifications for reminders and updates',
      status: 'completed',
      priority: 'medium',
      estimatedEffort: 'small',
      completedAt: Date.now() - 201600000,
    },
  ],
  addedRequirements: [],
  optionalAddOns: [
    { id: 'ff-addon-1', name: 'Meal Prep Guide', description: 'Automated meal preparation plans', status: 'added' },
    { id: 'ff-addon-2', name: 'Trainer Chat', description: 'Chat with certified fitness trainers', status: 'available' },
  ],
  suggestions: [],
  projectHealth: {
    clarity: 95,
    note: 'Excellent project definition. Almost ready for launch. Focus on final testing and polish.',
  },
  timeline: [
    { id: '1', label: 'Core features', completed: true, timestamp: Date.now() - 518400000 },
    { id: '2', label: 'Integration & social', completed: true, timestamp: Date.now() - 403200000 },
    { id: '3', label: 'Premium tier launch', completed: true, timestamp: Date.now() - 316800000 },
    { id: '4', label: 'Final testing & launch', completed: false },
  ],
  summary: 'A comprehensive fitness platform with AI-driven personalization, ready for market launch.',
  createdAt: Date.now() - 604800000,
  gitRepository: 'github.com/fitflow/app',
  commits: fitflowCommits,
  scopeAlerts: fitflowScopeAlerts,
  activities: fitflowActivities,
  developmentHealth: {
    score: 88,
    reasons: [
      'Excellent code quality and testing',
      'All core features completed',
      'Minimal scope creep',
      'Ready for production deployment',
      'Good stability and performance',
    ],
    lastUpdated: Date.now(),
  },
};
