import { Feedback, Product } from './types';

// 150+ realistic feedback entries from multiple sources
const FEEDBACK_ENTRIES: Feedback[] = [
  // Payment Issues (Bugs - High Priority)
  {
    id: 'fb-001',
    text: 'Payment fails with a cryptic error message. Support says it\'s a known issue but no timeline for fix.',
    userId: 'user-1',
    userName: 'Sarah Chen',
    date: Date.now() - 864000000, // ~10 days ago
    source: 'support',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'critical',
    status: 'in_progress',
  },
  {
    id: 'fb-002',
    text: 'My payment went through twice but I only see one order. Please help!',
    userId: 'user-2',
    userName: 'James Rodriguez',
    date: Date.now() - 777600000,
    source: 'support',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'critical',
    status: 'resolved',
  },
  {
    id: 'fb-003',
    text: 'Stripe integration error on checkout. Getting 502 Gateway error.',
    userId: 'user-3',
    userName: 'Emma Watson',
    date: Date.now() - 691200000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'critical',
    status: 'in_progress',
  },
  {
    id: 'fb-004',
    text: 'Cannot process payment with international credit cards - very limiting!',
    userId: 'user-4',
    userName: 'Marco Rossi',
    date: Date.now() - 604800000,
    source: 'support',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'feature',
    priority: 'high',
    status: 'planned',
  },
  {
    id: 'fb-005',
    text: 'Payment methods not saving properly. Have to re-enter every time.',
    userId: 'user-5',
    userName: 'Lisa Anderson',
    date: Date.now() - 518400000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'high',
    status: 'in_progress',
  },

  // Crashes & Performance (Bugs)
  {
    id: 'fb-006',
    text: 'App crashes when browsing products on slow internet. Completely unusable.',
    userId: 'user-6',
    userName: 'David Kim',
    date: Date.now() - 864000000,
    source: 'review',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'critical',
    status: 'in_progress',
  },
  {
    id: 'fb-007',
    text: 'App crashes after adding 5+ items to cart. Losing orders this way.',
    userId: 'user-7',
    userName: 'Sophie Laurent',
    date: Date.now() - 777600000,
    source: 'support',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'critical',
    status: 'in_progress',
  },
  {
    id: 'fb-008',
    text: 'Slow loading on product pages - takes 5+ seconds. Need optimization.',
    userId: 'user-8',
    userName: 'Michael Park',
    date: Date.now() - 604800000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'performance',
    aiClassification: 'performance',
    priority: 'high',
    status: 'reviewing',
  },
  {
    id: 'fb-009',
    text: 'Images take forever to load on mobile. Gives bad first impression.',
    userId: 'user-9',
    userName: 'Jennifer Lee',
    date: Date.now() - 518400000,
    source: 'review',
    sentiment: 'negative',
    category: 'performance',
    aiClassification: 'performance',
    priority: 'high',
    status: 'planned',
  },
  {
    id: 'fb-010',
    text: 'Frequent timeouts on checkout. Lost 3 sales last week.',
    userId: 'user-10',
    userName: 'Robert Thompson',
    date: Date.now() - 432000000,
    source: 'support',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'performance',
    priority: 'critical',
    status: 'in_progress',
  },

  // UX Issues
  {
    id: 'fb-011',
    text: 'Search doesn\'t work as expected. Typo tolerance would be great.',
    userId: 'user-11',
    userName: 'Patricia Martinez',
    date: Date.now() - 864000000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-012',
    text: 'Can\'t figure out how to apply discount codes. UX is confusing.',
    userId: 'user-12',
    userName: 'Christopher Lee',
    date: Date.now() - 777600000,
    source: 'support',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-013',
    text: 'Where is the order history? Can\'t find past purchases.',
    userId: 'user-13',
    userName: 'Amanda White',
    date: Date.now() - 691200000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },
  {
    id: 'fb-014',
    text: 'Wishlist feature doesn\'t sync across devices. Very inconvenient.',
    userId: 'user-14',
    userName: 'Kevin Garcia',
    date: Date.now() - 604800000,
    source: 'review',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-015',
    text: 'Navigation menu is hidden too well on mobile. Hard to find anything.',
    userId: 'user-15',
    userName: 'Michelle Brown',
    date: Date.now() - 518400000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'medium',
    status: 'reviewing',
  },

  // Feature Requests (High Volume)
  {
    id: 'fb-016',
    text: 'Please add dark mode! Using the app at night hurts my eyes.',
    userId: 'user-16',
    userName: 'Daniel Johnson',
    date: Date.now() - 864000000,
    source: 'in_app',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-017',
    text: 'Dark mode would be amazing! Please implement.',
    userId: 'user-17',
    userName: 'Rachel Green',
    date: Date.now() - 777600000,
    source: 'social',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },
  {
    id: 'fb-018',
    text: 'Want dark mode option. Eyes getting tired of bright interface.',
    userId: 'user-18',
    userName: 'Tom Harris',
    date: Date.now() - 604800000,
    source: 'review',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },
  {
    id: 'fb-019',
    text: 'Can we have notifications for price drops? Very interested in this.',
    userId: 'user-19',
    userName: 'Laura Clark',
    date: Date.now() - 518400000,
    source: 'in_app',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-020',
    text: 'Price drop alerts would make me use the app daily.',
    userId: 'user-20',
    userName: 'Steven Miller',
    date: Date.now() - 432000000,
    source: 'survey',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },

  // Export & Reporting
  {
    id: 'fb-021',
    text: 'Need ability to export order data to CSV for accounting.',
    userId: 'user-21',
    userName: 'Rebecca Davis',
    date: Date.now() - 864000000,
    source: 'support',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'high',
    status: 'reviewing',
  },
  {
    id: 'fb-022',
    text: 'Can we export purchase history? Need it for taxes.',
    userId: 'user-22',
    userName: 'Andrew Wilson',
    date: Date.now() - 777600000,
    source: 'in_app',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'high',
    status: 'planned',
  },
  {
    id: 'fb-023',
    text: 'Export feature would help me reconcile my records.',
    userId: 'user-23',
    userName: 'Karen Moore',
    date: Date.now() - 604800000,
    source: 'support',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'high',
    status: 'planned',
  },

  // Mobile App
  {
    id: 'fb-024',
    text: 'Please release a native iOS app. Web version is clunky on iPhone.',
    userId: 'user-24',
    userName: 'Susan Taylor',
    date: Date.now() - 864000000,
    source: 'social',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'high',
    status: 'planned',
  },
  {
    id: 'fb-025',
    text: 'Would love a proper iOS app instead of web wrapper.',
    userId: 'user-25',
    userName: 'Mark Jackson',
    date: Date.now() - 691200000,
    source: 'review',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'high',
    status: 'planned',
  },
  {
    id: 'fb-026',
    text: 'Native Android app would be fantastic for on-the-go shopping.',
    userId: 'user-26',
    userName: 'Diana White',
    date: Date.now() - 604800000,
    source: 'in_app',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'high',
    status: 'planned',
  },

  // Positive Feedback
  {
    id: 'fb-027',
    text: 'Love the product! Interface is clean and easy to use.',
    userId: 'user-27',
    userName: 'Nicholas Young',
    date: Date.now() - 864000000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-028',
    text: 'Excellent shopping experience! Will recommend to friends.',
    userId: 'user-28',
    userName: 'Olivia Martin',
    date: Date.now() - 777600000,
    source: 'in_app',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-029',
    text: 'Great selection and fast checkout. Very happy!',
    userId: 'user-29',
    userName: 'Ryan Harris',
    date: Date.now() - 691200000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-030',
    text: 'The recommendation engine is surprisingly good!',
    userId: 'user-30',
    userName: 'Sophia Wilson',
    date: Date.now() - 604800000,
    source: 'social',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },

  // Notifications (5+ entries)
  {
    id: 'fb-031',
    text: 'Would love push notifications when items go on sale.',
    userId: 'user-31',
    userName: 'Justin Lee',
    date: Date.now() - 777600000,
    source: 'in_app',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-032',
    text: 'Notifications for back-in-stock items would be helpful.',
    userId: 'user-32',
    userName: 'Maria Garcia',
    date: Date.now() - 691200000,
    source: 'support',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },
  {
    id: 'fb-033',
    text: 'Email notifications for order updates are inconsistent.',
    userId: 'user-33',
    userName: 'Brian Evans',
    date: Date.now() - 604800000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-034',
    text: 'No notification when my order shipped. Found out 3 days late.',
    userId: 'user-34',
    userName: 'Angela Moore',
    date: Date.now() - 518400000,
    source: 'support',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'high',
    status: 'in_progress',
  },
  {
    id: 'fb-035',
    text: 'Would like SMS notifications in addition to email.',
    userId: 'user-35',
    userName: 'William Turner',
    date: Date.now() - 432000000,
    source: 'survey',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'reviewing',
  },

  // Checkout Experience (5+ entries)
  {
    id: 'fb-036',
    text: 'Checkout is too many steps. Should be one-click buying.',
    userId: 'user-36',
    userName: 'Lisa Anderson',
    date: Date.now() - 864000000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-037',
    text: 'Checkout process is complex. Lost multiple sales.',
    userId: 'user-37',
    userName: 'Kevin Martin',
    date: Date.now() - 777600000,
    source: 'support',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'high',
    status: 'reviewing',
  },
  {
    id: 'fb-038',
    text: 'Guest checkout option would be great. Don\'t want to create account.',
    userId: 'user-38',
    userName: 'Nicole Johnson',
    date: Date.now() - 691200000,
    source: 'in_app',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'high',
    status: 'planned',
  },
  {
    id: 'fb-039',
    text: 'Abandoned checkout because sign-up was mandatory.',
    userId: 'user-39',
    userName: 'Thomas Garcia',
    date: Date.now() - 604800000,
    source: 'social',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'feature',
    priority: 'high',
    status: 'reviewing',
  },
  {
    id: 'fb-040',
    text: 'Express checkout saves time. Love the saved cards feature.',
    userId: 'user-40',
    userName: 'Cassandra Davis',
    date: Date.now() - 518400000,
    source: 'in_app',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },

  // Account & Auth Issues
  {
    id: 'fb-041',
    text: 'Forgot password reset email never arrives.',
    userId: 'user-41',
    userName: 'Edward Wilson',
    date: Date.now() - 864000000,
    source: 'support',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'high',
    status: 'in_progress',
  },
  {
    id: 'fb-042',
    text: 'Session timeout happens too quickly. Logged out mid-purchase.',
    userId: 'user-42',
    userName: 'Patricia Brown',
    date: Date.now() - 777600000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'ux',
    priority: 'high',
    status: 'reviewing',
  },
  {
    id: 'fb-043',
    text: 'Two-factor authentication is confusing. Too many hoops to jump.',
    userId: 'user-43',
    userName: 'George Martinez',
    date: Date.now() - 691200000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-044',
    text: 'Social login options would be convenient.',
    userId: 'user-44',
    userName: 'Heather Taylor',
    date: Date.now() - 604800000,
    source: 'survey',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },

  // Search & Discovery
  {
    id: 'fb-045',
    text: 'Product search is broken. Searching for "red dress" returns unrelated items.',
    userId: 'user-45',
    userName: 'Isaac Thompson',
    date: Date.now() - 864000000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'high',
    status: 'in_progress',
  },
  {
    id: 'fb-046',
    text: 'Filter by price range doesn\'t work properly.',
    userId: 'user-46',
    userName: 'Julia Anderson',
    date: Date.now() - 777600000,
    source: 'support',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'high',
    status: 'in_progress',
  },
  {
    id: 'fb-047',
    text: 'Wish there were more sorting options. Can\'t find popular items.',
    userId: 'user-47',
    userName: 'Kevin Bennett',
    date: Date.now() - 691200000,
    source: 'in_app',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },
  {
    id: 'fb-048',
    text: 'Personalized recommendations are amazing! Keep doing this.',
    userId: 'user-48',
    userName: 'Linda Roberts',
    date: Date.now() - 604800000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-049',
    text: 'Hard to discover new products. Algorithm needs work.',
    userId: 'user-49',
    userName: 'Matthew Edwards',
    date: Date.now() - 518400000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'medium',
    status: 'reviewing',
  },

  // Customer Support
  {
    id: 'fb-050',
    text: 'Waited 48 hours for support response. Very disappointed.',
    userId: 'user-50',
    userName: 'Nancy Collins',
    date: Date.now() - 864000000,
    source: 'support',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'high',
    status: 'reviewing',
  },
  {
    id: 'fb-051',
    text: 'Support team was very helpful and resolved issue quickly.',
    userId: 'user-51',
    userName: 'Paul Stewart',
    date: Date.now() - 777600000,
    source: 'survey',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-052',
    text: 'No live chat support. Would help resolve issues faster.',
    userId: 'user-52',
    userName: 'Rebecca Harris',
    date: Date.now() - 691200000,
    source: 'in_app',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },
  {
    id: 'fb-053',
    text: 'Live chat support would be game-changing.',
    userId: 'user-53',
    userName: 'Daniel Bell',
    date: Date.now() - 604800000,
    source: 'survey',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },

  // Product Catalog Issues
  {
    id: 'fb-054',
    text: 'Products out of stock but still showing as available.',
    userId: 'user-54',
    userName: 'Emily Murphy',
    date: Date.now() - 864000000,
    source: 'support',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'high',
    status: 'in_progress',
  },
  {
    id: 'fb-055',
    text: 'Product images are low quality. Can\'t see details properly.',
    userId: 'user-55',
    userName: 'Joshua Lopez',
    date: Date.now() - 777600000,
    source: 'review',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-056',
    text: 'Product descriptions are vague. Need more details.',
    userId: 'user-56',
    userName: 'Victoria Ross',
    date: Date.now() - 691200000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-057',
    text: 'Wish there were size guides and more product photos.',
    userId: 'user-57',
    userName: 'Luke Henderson',
    date: Date.now() - 604800000,
    source: 'survey',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },

  // Shipping & Delivery
  {
    id: 'fb-058',
    text: 'Shipping took 3 weeks. Expected it much sooner.',
    userId: 'user-58',
    userName: 'Grace Campbell',
    date: Date.now() - 777600000,
    source: 'review',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'medium',
    status: 'new',
  },
  {
    id: 'fb-059',
    text: 'Tracking is inaccurate. Doesn\'t update properly.',
    userId: 'user-59',
    userName: 'Henry Parker',
    date: Date.now() - 691200000,
    source: 'support',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'high',
    status: 'reviewing',
  },
  {
    id: 'fb-060',
    text: 'Real-time tracking would be helpful.',
    userId: 'user-60',
    userName: 'Iris Wright',
    date: Date.now() - 604800000,
    source: 'in_app',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },

  // Browser & Device Compatibility
  {
    id: 'fb-061',
    text: 'Doesn\'t work on Safari. Only works on Chrome.',
    userId: 'user-61',
    userName: 'Jack Murphy',
    date: Date.now() - 864000000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'high',
    status: 'in_progress',
  },
  {
    id: 'fb-062',
    text: 'Mobile experience is terrible on tablets.',
    userId: 'user-62',
    userName: 'Katie Hayes',
    date: Date.now() - 777600000,
    source: 'review',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'ux',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-063',
    text: 'Firefox compatibility would be great.',
    userId: 'user-63',
    userName: 'Leo Morgan',
    date: Date.now() - 604800000,
    source: 'survey',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'low',
    status: 'planned',
  },

  // Accessibility
  {
    id: 'fb-064',
    text: 'App is not accessible for screen reader users.',
    userId: 'user-64',
    userName: 'Megan Foster',
    date: Date.now() - 691200000,
    source: 'support',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'high',
    status: 'planned',
  },
  {
    id: 'fb-065',
    text: 'Text size is too small. Can\'t read on mobile.',
    userId: 'user-65',
    userName: 'Nathan Bell',
    date: Date.now() - 604800000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'medium',
    status: 'reviewing',
  },

  // API & Integration
  {
    id: 'fb-066',
    text: 'API documentation is poor. Hard to integrate.',
    userId: 'user-66',
    userName: 'Olivia Scott',
    date: Date.now() - 777600000,
    source: 'support',
    sentiment: 'negative',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-067',
    text: 'Need better API rate limits for high-volume integrations.',
    userId: 'user-67',
    userName: 'Peter Adams',
    date: Date.now() - 604800000,
    source: 'support',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },

  // Reviews & Ratings
  {
    id: 'fb-068',
    text: 'Reviews seem fake. Many too positive, looks manipulated.',
    userId: 'user-68',
    userName: 'Quinn Matthews',
    date: Date.now() - 691200000,
    source: 'review',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-069',
    text: 'Would like to see verified purchase badges on reviews.',
    userId: 'user-69',
    userName: 'Rachel Stone',
    date: Date.now() - 604800000,
    source: 'survey',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },

  // Promotions & Discounts
  {
    id: 'fb-070',
    text: 'Discount codes rarely work. Always get error messages.',
    userId: 'user-70',
    userName: 'Samuel Young',
    date: Date.now() - 777600000,
    source: 'support',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'high',
    status: 'in_progress',
  },
  {
    id: 'fb-071',
    text: 'Where are the sales and promotions? Need better discounts.',
    userId: 'user-71',
    userName: 'Tina Harris',
    date: Date.now() - 604800000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'low',
    status: 'reviewing',
  },

  // User Accounts (More)
  {
    id: 'fb-072',
    text: 'Address book is limited. Need to manage multiple addresses.',
    userId: 'user-72',
    userName: 'Uma Patel',
    date: Date.now() - 691200000,
    source: 'in_app',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },
  {
    id: 'fb-073',
    text: 'Profile page is great. Easy to manage account settings.',
    userId: 'user-73',
    userName: 'Vincent Scott',
    date: Date.now() - 604800000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },

  // Cart & Wishlist
  {
    id: 'fb-074',
    text: 'Cart empties when I navigate away. Lost my entire shopping session.',
    userId: 'user-74',
    userName: 'Wendy Foster',
    date: Date.now() - 777600000,
    source: 'support',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'critical',
    status: 'in_progress',
  },
  {
    id: 'fb-075',
    text: 'Wishlist is very useful. Love being able to save items.',
    userId: 'user-75',
    userName: 'Xavier Thompson',
    date: Date.now() - 604800000,
    source: 'in_app',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },

  // Trending Features (Additional)
  {
    id: 'fb-076',
    text: 'Abandoned cart recovery email helped me complete purchase!',
    userId: 'user-76',
    userName: 'Yara Martinez',
    date: Date.now() - 604800000,
    source: 'social',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-077',
    text: 'Abandoned cart emails are spammy. Stop sending them.',
    userId: 'user-77',
    userName: 'Zack Williams',
    date: Date.now() - 518400000,
    source: 'review',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'low',
    status: 'reviewing',
  },

  // Analytics & Reporting (Biz Users)
  {
    id: 'fb-078',
    text: 'Need better sales analytics dashboard for business users.',
    userId: 'user-78',
    userName: 'Alice Robertson',
    date: Date.now() - 691200000,
    source: 'interview',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'high',
    status: 'planned',
  },
  {
    id: 'fb-079',
    text: 'Sales reports would help track inventory better.',
    userId: 'user-79',
    userName: 'Bob Sullivan',
    date: Date.now() - 604800000,
    source: 'interview',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'high',
    status: 'planned',
  },

  // Email & Communication
  {
    id: 'fb-080',
    text: 'Transactional emails not formatted properly on mobile.',
    userId: 'user-80',
    userName: 'Chloe Turner',
    date: Date.now() - 604800000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-081',
    text: 'Newsletter frequency is too high. Unsubscribed.',
    userId: 'user-81',
    userName: 'Dominic Perry',
    date: Date.now() - 518400000,
    source: 'social',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'low',
    status: 'reviewing',
  },

  // Security Concerns
  {
    id: 'fb-082',
    text: 'Concerned about data privacy. Who owns my information?',
    userId: 'user-82',
    userName: 'Eleanor Green',
    date: Date.now() - 691200000,
    source: 'support',
    sentiment: 'negative',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'high',
    status: 'new',
  },
  {
    id: 'fb-083',
    text: 'Please add GDPR data export functionality.',
    userId: 'user-83',
    userName: 'Felix Baker',
    date: Date.now() - 604800000,
    source: 'support',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'high',
    status: 'planned',
  },

  // Bulk Operations
  {
    id: 'fb-084',
    text: 'Would like to add multiple items to cart at once from wishlist.',
    userId: 'user-84',
    userName: 'Grace Harvey',
    date: Date.now() - 604800000,
    source: 'in_app',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'low',
    status: 'planned',
  },
  {
    id: 'fb-085',
    text: 'Bulk edit wish list items - remove multiple at once.',
    userId: 'user-85',
    userName: 'Henry Morgan',
    date: Date.now() - 518400000,
    source: 'survey',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'low',
    status: 'planned',
  },

  // Recent Positive Trends
  {
    id: 'fb-086',
    text: 'Recent update really improved app stability!',
    userId: 'user-86',
    userName: 'Iris Mitchell',
    date: Date.now() - 345600000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-087',
    text: 'Performance is so much better after the latest release.',
    userId: 'user-87',
    userName: 'Jack Robinson',
    date: Date.now() - 259200000,
    source: 'in_app',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-088',
    text: 'Happy to see bug fixes rolling out regularly. Keep it up!',
    userId: 'user-88',
    userName: 'Katie Bell',
    date: Date.now() - 172800000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },

  // Recent Negative Trends
  {
    id: 'fb-089',
    text: 'Latest update broke my workflow. Reverting to old version.',
    userId: 'user-89',
    userName: 'Leo Zhang',
    date: Date.now() - 259200000,
    source: 'social',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'critical',
    status: 'in_progress',
  },
  {
    id: 'fb-090',
    text: 'Recent changes made the UI confusing. Preferred the old design.',
    userId: 'user-90',
    userName: 'Mia Johnson',
    date: Date.now() - 172800000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'medium',
    status: 'reviewing',
  },

  // More Bug Reports
  {
    id: 'fb-091',
    text: 'Numbers on reports don\'t add up correctly. Math is broken.',
    userId: 'user-91',
    userName: 'Noah White',
    date: Date.now() - 604800000,
    source: 'support',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'critical',
    status: 'in_progress',
  },
  {
    id: 'fb-092',
    text: 'Duplicate entries in order history.',
    userId: 'user-92',
    userName: 'Olivia Black',
    date: Date.now() - 518400000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-093',
    text: 'Spelling errors in product descriptions.',
    userId: 'user-93',
    userName: 'Paul Gray',
    date: Date.now() - 432000000,
    source: 'review',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'low',
    status: 'reviewing',
  },

  // More Feature Requests
  {
    id: 'fb-094',
    text: 'Would love browser extensions for quick shopping.',
    userId: 'user-94',
    userName: 'Quinn Kelly',
    date: Date.now() - 604800000,
    source: 'survey',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'low',
    status: 'planned',
  },
  {
    id: 'fb-095',
    text: 'Voice search would be convenient.',
    userId: 'user-95',
    userName: 'Rachel Stone',
    date: Date.now() - 518400000,
    source: 'in_app',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'low',
    status: 'planned',
  },
  {
    id: 'fb-096',
    text: 'QR codes for quick product access would be cool.',
    userId: 'user-96',
    userName: 'Samuel Davis',
    date: Date.now() - 432000000,
    source: 'survey',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'low',
    status: 'planned',
  },
  {
    id: 'fb-097',
    text: 'Augmented reality try-on feature would be amazing.',
    userId: 'user-97',
    userName: 'Tina White',
    date: Date.now() - 345600000,
    source: 'interview',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },
  {
    id: 'fb-098',
    text: 'Video product demonstrations would help with purchase decisions.',
    userId: 'user-98',
    userName: 'Uma Grant',
    date: Date.now() - 259200000,
    source: 'survey',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },
  {
    id: 'fb-099',
    text: 'Wish I could see user-generated content/photos of products.',
    userId: 'user-99',
    userName: 'Victor Brown',
    date: Date.now() - 172800000,
    source: 'in_app',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },
  {
    id: 'fb-100',
    text: 'Size comparison chart between brands would be helpful.',
    userId: 'user-100',
    userName: 'Wendy Scott',
    date: Date.now() - 86400000,
    source: 'survey',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },

  // Performance Variations
  {
    id: 'fb-101',
    text: 'App speed varies depending on time of day. Noon is worst.',
    userId: 'user-101',
    userName: 'Xavier Lee',
    date: Date.now() - 604800000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'performance',
    aiClassification: 'performance',
    priority: 'high',
    status: 'reviewing',
  },
  {
    id: 'fb-102',
    text: 'App uses too much battery. Closes before I\'m done shopping.',
    userId: 'user-102',
    userName: 'Yara Lewis',
    date: Date.now() - 518400000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'performance',
    aiClassification: 'performance',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-103',
    text: 'High data usage on mobile. Not friendly to data-limited plans.',
    userId: 'user-103',
    userName: 'Zachary Hill',
    date: Date.now() - 432000000,
    source: 'support',
    sentiment: 'negative',
    category: 'performance',
    aiClassification: 'performance',
    priority: 'medium',
    status: 'planned',
  },

  // Internationalization
  {
    id: 'fb-104',
    text: 'App is only in English. Need Spanish support.',
    userId: 'user-104',
    userName: 'Alba Martinez',
    date: Date.now() - 604800000,
    source: 'support',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },
  {
    id: 'fb-105',
    text: 'Would love German language option.',
    userId: 'user-105',
    userName: 'Bruno Schmidt',
    date: Date.now() - 518400000,
    source: 'survey',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },
  {
    id: 'fb-106',
    text: 'Multiple currency support for international customers.',
    userId: 'user-106',
    userName: 'Celine Dubois',
    date: Date.now() - 432000000,
    source: 'interview',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'high',
    status: 'planned',
  },

  // Business Features
  {
    id: 'fb-107',
    text: 'Need bulk ordering capability for business customers.',
    userId: 'user-107',
    userName: 'David Chen',
    date: Date.now() - 604800000,
    source: 'support',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'high',
    status: 'planned',
  },
  {
    id: 'fb-108',
    text: 'B2B pricing tiers would be valuable.',
    userId: 'user-108',
    userName: 'Eleanor Cooper',
    date: Date.now() - 518400000,
    source: 'interview',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'high',
    status: 'planned',
  },
  {
    id: 'fb-109',
    text: 'Net payment terms for business accounts would help.',
    userId: 'user-109',
    userName: 'Frank Miller',
    date: Date.now() - 432000000,
    source: 'interview',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'high',
    status: 'planned',
  },

  // Additional Positive Feedback
  {
    id: 'fb-110',
    text: 'Interface is intuitive. No confusion at all.',
    userId: 'user-110',
    userName: 'Grace Wilson',
    date: Date.now() - 432000000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-111',
    text: 'Product quality is consistently excellent.',
    userId: 'user-111',
    userName: 'Henry Adams',
    date: Date.now() - 345600000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-112',
    text: 'Fast shipping! Will definitely order again.',
    userId: 'user-112',
    userName: 'Ivy Roberts',
    date: Date.now() - 259200000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-113',
    text: 'Customer service went above and beyond for me.',
    userId: 'user-113',
    userName: 'Jack Taylor',
    date: Date.now() - 172800000,
    source: 'social',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-114',
    text: 'Best shopping experience I\'ve had online.',
    userId: 'user-114',
    userName: 'Karen White',
    date: Date.now() - 86400000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },

  // Return & Refund Issues
  {
    id: 'fb-115',
    text: 'Return process is complicated. Should be simpler.',
    userId: 'user-115',
    userName: 'Leo Young',
    date: Date.now() - 604800000,
    source: 'support',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'high',
    status: 'reviewing',
  },
  {
    id: 'fb-116',
    text: 'Waiting for refund is taking too long.',
    userId: 'user-116',
    userName: 'Megan Wilson',
    date: Date.now() - 518400000,
    source: 'support',
    sentiment: 'negative',
    category: 'ux',
    aiClassification: 'ux',
    priority: 'high',
    status: 'reviewing',
  },
  {
    id: 'fb-117',
    text: 'Free returns would make me shop more frequently.',
    userId: 'user-117',
    userName: 'Nathan Lopez',
    date: Date.now() - 432000000,
    source: 'survey',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'medium',
    status: 'planned',
  },

  // Social Features
  {
    id: 'fb-118',
    text: 'Would love to share wishlists with friends.',
    userId: 'user-118',
    userName: 'Olivia Garcia',
    date: Date.now() - 604800000,
    source: 'in_app',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'low',
    status: 'planned',
  },
  {
    id: 'fb-119',
    text: 'Social login makes checkout easier for me.',
    userId: 'user-119',
    userName: 'Peter Thompson',
    date: Date.now() - 518400000,
    source: 'in_app',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-120',
    text: 'Group buying feature for friends would be nice.',
    userId: 'user-120',
    userName: 'Quinn Davis',
    date: Date.now() - 432000000,
    source: 'survey',
    sentiment: 'neutral',
    category: 'feature',
    aiClassification: 'feature',
    priority: 'low',
    status: 'planned',
  },

  // Summary/Misc
  {
    id: 'fb-121',
    text: 'App deserves 5 stars! Highly recommend.',
    userId: 'user-121',
    userName: 'Rachel Brown',
    date: Date.now() - 86400000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },

  // Additional positive feedback (rounding out sentiment distribution)
  {
    id: 'fb-122',
    text: 'Checkout redesign is fantastic. So much faster now.',
    userId: 'user-122',
    userName: 'Aaron Phillips',
    date: Date.now() - 604800000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-123',
    text: 'Love how easy it is to track my order status now.',
    userId: 'user-123',
    userName: 'Bella Simmons',
    date: Date.now() - 518400000,
    source: 'in_app',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-124',
    text: 'The wishlist and cart sync perfectly across my devices now. Great fix!',
    userId: 'user-124',
    userName: 'Carlos Mendez',
    date: Date.now() - 432000000,
    source: 'in_app',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-125',
    text: 'Product recommendations feel spot-on lately. Really impressed.',
    userId: 'user-125',
    userName: 'Diana Foster',
    date: Date.now() - 345600000,
    source: 'social',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-126',
    text: 'Support resolved my billing issue in minutes. Excellent service.',
    userId: 'user-126',
    userName: 'Ethan Brooks',
    date: Date.now() - 259200000,
    source: 'support',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-127',
    text: 'The new search results are so much more relevant. Well done.',
    userId: 'user-127',
    userName: 'Fiona Hayes',
    date: Date.now() - 172800000,
    source: 'in_app',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-128',
    text: 'Really appreciate the transparency around shipping timelines now.',
    userId: 'user-128',
    userName: 'Gabriel Ortiz',
    date: Date.now() - 86400000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-129',
    text: 'Beautifully designed app. Everything feels polished.',
    userId: 'user-129',
    userName: 'Hannah Reid',
    date: Date.now() - 691200000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-130',
    text: 'Great value for money. Prices are competitive and quality is high.',
    userId: 'user-130',
    userName: 'Ian Walsh',
    date: Date.now() - 604800000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-131',
    text: 'Saved cards and addresses made repeat purchases painless.',
    userId: 'user-131',
    userName: 'Jasmine Cole',
    date: Date.now() - 518400000,
    source: 'in_app',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-132',
    text: 'The onboarding flow was smooth and quick. Great first impression.',
    userId: 'user-132',
    userName: 'Kyle Foster',
    date: Date.now() - 432000000,
    source: 'survey',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-133',
    text: 'Customer support genuinely cares. Best experience I\'ve had with any retailer.',
    userId: 'user-133',
    userName: 'Lena Ford',
    date: Date.now() - 345600000,
    source: 'social',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-134',
    text: 'App feels noticeably snappier since the last update.',
    userId: 'user-134',
    userName: 'Mason Reyes',
    date: Date.now() - 259200000,
    source: 'in_app',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-135',
    text: 'Refund was processed faster than expected. Nice surprise.',
    userId: 'user-135',
    userName: 'Nora Blake',
    date: Date.now() - 172800000,
    source: 'support',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-136',
    text: 'Really like the new product photography. Much clearer now.',
    userId: 'user-136',
    userName: 'Oscar Diaz',
    date: Date.now() - 86400000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-137',
    text: 'The loyalty points system is a nice touch. Keeps me coming back.',
    userId: 'user-137',
    userName: 'Priya Nair',
    date: Date.now() - 604800000,
    source: 'in_app',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-138',
    text: 'App works flawlessly on my tablet now. Thanks for fixing that.',
    userId: 'user-138',
    userName: 'Quentin Marsh',
    date: Date.now() - 518400000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-139',
    text: 'Order arrived earlier than the estimate. Very pleased.',
    userId: 'user-139',
    userName: 'Ruth Alvarez',
    date: Date.now() - 432000000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-140',
    text: 'Two-factor login is quick now, glad they simplified it.',
    userId: 'user-140',
    userName: 'Sean Whitfield',
    date: Date.now() - 345600000,
    source: 'in_app',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-141',
    text: 'The interview team was great, I feel heard as a customer.',
    userId: 'user-141',
    userName: 'Talia Vance',
    date: Date.now() - 259200000,
    source: 'interview',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-142',
    text: 'Dark corners of the UI got polished up nicely this release.',
    userId: 'user-142',
    userName: 'Umar Farooq',
    date: Date.now() - 172800000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-143',
    text: 'Fast and reliable. Never had an issue with an order.',
    userId: 'user-143',
    userName: 'Vera vittorio',
    date: Date.now() - 86400000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-144',
    text: 'Product bundles saved me a lot of money this month. Nice feature.',
    userId: 'user-144',
    userName: 'Walter Simmons',
    date: Date.now() - 604800000,
    source: 'in_app',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-145',
    text: 'Impressed with how quickly the team shipped bug fixes this sprint.',
    userId: 'user-145',
    userName: 'Ximena Cruz',
    date: Date.now() - 518400000,
    source: 'social',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-146',
    text: 'Great experience overall, will keep shopping here.',
    userId: 'user-146',
    userName: 'Yusuf Karimi',
    date: Date.now() - 432000000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-147',
    text: 'Loved the personalized homepage layout after the update.',
    userId: 'user-147',
    userName: 'Zoe Bennett',
    date: Date.now() - 345600000,
    source: 'in_app',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-148',
    text: 'The size guide addition made buying clothes online so much easier.',
    userId: 'user-148',
    userName: 'Aiden Foster',
    date: Date.now() - 259200000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-149',
    text: 'Great job on accessibility improvements, screen reader works well now.',
    userId: 'user-149',
    userName: 'Brianna Cole',
    date: Date.now() - 172800000,
    source: 'support',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-150',
    text: 'Consistently good experience across web and mobile.',
    userId: 'user-150',
    userName: 'Caleb Nash',
    date: Date.now() - 86400000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-151',
    text: 'Pleasantly surprised by how responsive the live chat was.',
    userId: 'user-151',
    userName: 'Delilah Moss',
    date: Date.now() - 604800000,
    source: 'support',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-152',
    text: 'This is now my go-to shopping app. Never disappoints.',
    userId: 'user-152',
    userName: 'Elias Grant',
    date: Date.now() - 518400000,
    source: 'social',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-153',
    text: 'Great communication throughout the delivery process.',
    userId: 'user-153',
    userName: 'Freya Douglas',
    date: Date.now() - 432000000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-154',
    text: 'Love that I can now export my order history to CSV. Exactly what I needed.',
    userId: 'user-154',
    userName: 'Gideon Pratt',
    date: Date.now() - 345600000,
    source: 'in_app',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-155',
    text: 'App runs great on my older phone too, no lag at all.',
    userId: 'user-155',
    userName: 'Harper Lin',
    date: Date.now() - 259200000,
    source: 'review',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-156',
    text: 'Multi-language support finally arrived and it works great!',
    userId: 'user-156',
    userName: 'Ines Dupont',
    date: Date.now() - 172800000,
    source: 'in_app',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },
  {
    id: 'fb-157',
    text: 'Team clearly listens to feedback, several of my requests got shipped.',
    userId: 'user-157',
    userName: 'Jonah Wexler',
    date: Date.now() - 86400000,
    source: 'social',
    sentiment: 'positive',
    category: 'positive',
    aiClassification: 'positive',
    priority: 'low',
    status: 'new',
  },

  // Additional negative feedback (rounding out sentiment distribution)
  {
    id: 'fb-158',
    text: 'App logged me out randomly mid-checkout again. Second time this week.',
    userId: 'user-158',
    userName: 'Klara Beck',
    date: Date.now() - 604800000,
    source: 'support',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'high',
    status: 'reviewing',
  },
  {
    id: 'fb-159',
    text: 'Coupon stacking is broken, codes cancel each other out unexpectedly.',
    userId: 'user-159',
    userName: 'Liam Osei',
    date: Date.now() - 518400000,
    source: 'support',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-160',
    text: 'Product variant selector resets when I change quantity. Frustrating bug.',
    userId: 'user-160',
    userName: 'Maya Solberg',
    date: Date.now() - 432000000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-161',
    text: 'App freezes completely when switching between tabs quickly.',
    userId: 'user-161',
    userName: 'Noel Ashford',
    date: Date.now() - 345600000,
    source: 'review',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'critical',
    status: 'in_progress',
  },
  {
    id: 'fb-162',
    text: 'Getting billed in the wrong currency despite setting my region correctly.',
    userId: 'user-162',
    userName: 'Opal Fernsby',
    date: Date.now() - 259200000,
    source: 'support',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'high',
    status: 'in_progress',
  },
  {
    id: 'fb-163',
    text: 'Search autocomplete suggests discontinued products. Confusing and wastes time.',
    userId: 'user-163',
    userName: 'Preston Lowe',
    date: Date.now() - 172800000,
    source: 'in_app',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-164',
    text: 'Push notification permissions dialog appears every single launch. Very annoying.',
    userId: 'user-164',
    userName: 'Quincy Delgado',
    date: Date.now() - 86400000,
    source: 'review',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'medium',
    status: 'reviewing',
  },
  {
    id: 'fb-165',
    text: 'Lost my saved payment method after the last app update. Had to re-add everything.',
    userId: 'user-165',
    userName: 'Rosalind Kemp',
    date: Date.now() - 604800000,
    source: 'support',
    sentiment: 'negative',
    category: 'bug',
    aiClassification: 'bug',
    priority: 'high',
    status: 'in_progress',
  },
];

export const MOCK_FEEDBACK = FEEDBACK_ENTRIES;

// Mock Product with Analytics
export const DEMO_PRODUCT: Product = {
  id: 'product-demo-001',
  name: 'StyleCart',
  description: 'E-commerce platform for fashion retail with advanced discovery and checkout',
  category: 'E-commerce',
  version: '2.1.3',
  totalUsers: 125000,
  activeUsers: 48200,
  metrics: {
    crashRate: 0.8, // percent
    avgResponseTime: 1200, // ms
    errorRate: 2.3, // percent
    satisfactionScore: 3.8, // out of 5
  },
  healthScore: 72, // Will be recalculated
  clusters: [], // Will be populated by feedback service
  insights: [], // Will be populated by feedback service
  requirements: [],
  createdAt: Date.now() - 7776000000, // ~90 days ago
};
